- hosts: web
  user: root
  sudo: true
  tasks:
  - name: upgrade packages
    command: apt-get update
- hosts: web
  user: root
  sudo: true
  tasks:
  - name: "install Ruby"
    apt: "pkg=ruby1.9.3"
  - name: "install nginx"
    apt: "pkg=nginx"
  - name: "install Git"
    apt: "pkg=git"
  - name: "install make"
    apt: "pkg=make"
  - name: install Bundler
    command: gem install bundler creates=/usr/local/bin/bundle
- hosts: web
  user: root
  tasks:
  - command: "git clone https://github.com/danielstutzman/online-ruby-tutor creates=/root/online-ruby-tutor"
  - command: "git pull chdir=/root/online-ruby-tutor"
  - command: "bundle install --deployment chdir=/root/online-ruby-tutor"
  - command: "mkdir -p tmp tmp/sockets tmp/pids log chdir=/root/online-ruby-tutor"
  - command: "git submodule init chdir=/root/online-ruby-tutor"
  - command: "git submodule update chdir=/root/online-ruby-tutor"
  - command: sh -c "if [ -e tmp/pids/unicorn.pid ]; then cat tmp/pids/unicorn.pid | xargs kill; rm tmp/pids/unicorn.pid; fi" chdir=/root/online-ruby-tutor
  - command: "bundle exec unicorn -c unicorn.rb -E development -D -l 0.0.0.0:3001 chdir=/root/online-ruby-tutor"
- hosts: web
  user: root
  sudo: true
  tasks:
  - copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  - command: service nginx restart
