- hosts: web
  user: root
  tasks:
  - command: "/usr/sbin/adduser deployer --disabled-password --gecos '' creates=/home/deployer"
  - command: mkdir /home/deployer/.ssh creates=/home/deployer/.ssh
  - command: chown deployer:deployer /home/deployer/.ssh
  - command: cp /root/.ssh/authorized_keys /home/deployer/.ssh/authorized_keys
  - command: chown deployer:deployer /home/deployer/.ssh/authorized_keys
  - command: chmod 0600 /home/deployer/.ssh/authorized_keys

  - command: apt-get update

  - apt: "pkg=ruby1.9.3"
  - apt: "pkg=nginx"
  - apt: "pkg=git"
  - apt: "pkg=make"

  - command: gem install bundler creates=/usr/local/bin/bundle

- hosts: web
  user: deployer
  tasks:
  - command: "git clone https://github.com/danielstutzman/online-ruby-tutor creates=/home/deployer/online-ruby-tutor"
  - command: "git pull chdir=/home/deployer/online-ruby-tutor"
  - command: "bundle install --deployment chdir=/home/deployer/online-ruby-tutor"
  - command: "mkdir -p tmp tmp/sockets tmp/pids log chdir=/home/deployer/online-ruby-tutor"
  - command: "git submodule init chdir=/home/deployer/online-ruby-tutor"
  - command: "git submodule update chdir=/home/deployer/online-ruby-tutor"
  - command: sh -c "if [ -e tmp/pids/unicorn.pid ]; then cat tmp/pids/unicorn.pid | xargs kill; rm tmp/pids/unicorn.pid; fi" chdir=/home/deployer/online-ruby-tutor
  - command: "bundle exec unicorn -c unicorn.rb -E production -D -l 0.0.0.0:3001 chdir=/home/deployer/online-ruby-tutor"


- hosts: web
  user: root
  tasks:
  - copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  - command: service nginx restart
