-
  name: integer literal
  form: numvar = num
  example: seconds_in_hour = 3600
  output: number
  inputs: number
-
  name: float literal
  form: numvar = num
  example: pi = 3.14
  output: number
  inputs: number
-
  name: addition
  tags: plus
  form: numvar = num + num
  example: assets = liabilities + equity
  output: number
  inputs: number, number
-
  name: subtraction
  tags: minus
  form: numvar = num - num
  example: equity = assets - liabilities
  output: number
  inputs: number, number
-
  name: multiplication
  tags: multiply, times
  form: numvar = num * num
  example: total = num_lines * price_per_line
  output: number
  inputs: number, number
-
  name: division (no remainder if both integers)
  tags: divide
  form: numvar = num / num
  example: estimate_per_line = total / num_lines
  output: number
  inputs: number, number
-
  name: convert object to string
  tags: interpolation, hash, curly, braces
  form: "strvar = \"#{obj}\""
  example: "age_string = \"#{age}\""
  output: string
  inputs: object
-
  name: add to number variable
  tags: increment, plus
  form: numvar += num
  example: total_charge += line_charge
  output: number
  inputs: number
-
  name: "output object and newline"
  tags: print
  form: puts obj
  example: puts first_name
  output: output
  inputs: object
